---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "ansible_key"
      instance_type: t2.micro
      security_group: default
      region: ap-southeast-2
      aws_access_key: "{{ec2_access_key}}"  
      aws_secret_key: "{{ec2_secret_key}}"      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-0474411b350de35fb", name: "ansible-node-1" } 
      - { image: "ami-0892a9c01908fafd1", name: "ansible-node-2" } 
      - { image: "ami-0892a9c01908fafd1", name: "ansible-node-3" }
